server:
  port: 8121
  forward-headers-strategy: framework
spring:
  datasource:
    password: bcb@1234
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/config-db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
      #dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time-zone: UTC